spring:
  h2:
    console:
      enabled: true
  datasource:
    account:
      driver-class-name: org.h2.Driver
      url: jdbc:h2:mem:account;DB_CLOSE_DELAY=-1;MODE=MySQL
      username: sa
      password: sa
